### ISSUE TITLE
Synchronization failure and Playlist malfunction

### ISSUE THREAD

**Issue by UnixCro** [nukeop/nuclear#1001]
Hi,

somehow I don't manage to sync local files with nuclear. There is always only one loading bar under macOS Big Sur. I restarted my computer several times and deleted and reinstalled the app.

https://user-images.githubusercontent.com/70098046/124364127-b7d25f80-dc3f-11eb-9e48-7149c145a66f.mp4

<br>

Any ideas how I can create playlists? It doesn't work for me ...

https://user-images.githubusercontent.com/70098046/124364555-86a75e80-dc42-11eb-868f-bb85565002ae.mp4

<br>

**A couple of songs are missing**

Unfortunately, due to the number of songs, I cannot display a picture, so please enter "Trippie Boi Songs" in Google and then enter the artist "Trippie Boi" in nuclear. If you compare it, unfortunately, a few songs are missing.

<br>

<h3>Suggestions for improvement</h3>

Continuous loop option

- I am currently not aware of the possibility of listening to a song on a loop, instead it is only possible to play it again when you have finished listening to the playlist.

No other songs

- <s>Every time I want to play a song, nuclear adds a few other songs even though I don't want them to be played back.</s> Fixed: Deactivate Autoradio ✅

https://user-images.githubusercontent.com/70098046/124447349-8feb1500-dd81-11eb-8abd-83af315dd9d4.mp4

<br>

Icon is too big

- If you take a closer look you can see that nuclear takes up more space than all the other icons. I don't know, but I think it's a little nicer when everything looks the same

<img width="443" alt="Bildschirmfoto 2021-07-05 um 11 07 57" src="https://user-images.githubusercontent.com/70098046/124447163-66ca8480-dd81-11eb-989a-2c3f7f0e4a3d.png">

Extension is not supported

- Since `.webm` is not supported by the standard video / music player of macOS, it would be very desirable if you could add `.aac` to `.mp3` otherwise you would have to always re-render the file or use a third-party program must get to play it.

![Bildschirmfoto 2021-07-03 um 21 08 54](https://user-images.githubusercontent.com/70098046/124364628-ffa6b600-dc42-11eb-9bec-0e11f3cb12d7.jpg)

<br>

Selection Buttons

- The three selection buttons on the top right of nuclear. With them is a full screen, a minimization that is forwarded to the dock as a window and an exit from nuclear. Isn't it possible to hide Nuclear normally instead of exiting and not keep it minimized as a window? 

![Bildschirmfoto 2021-07-03 um 21 13 39](https://user-images.githubusercontent.com/70098046/124364775-fd912700-dc43-11eb-926e-f0daaa3d68e9.jpg)

<br>

Missing network

- When the internet is down, nuclear will unfortunately not give any further information. How about if nuclear could provide information about a small field like spotify that currently lacks the internet.

<h3>Questions</h3>

Nuclear informs the operating system that the file extension `.mp4` should be opened with nuclear by default.

If you change it with the `option key` then `Always open with` then the standard remains with nuclear. 

How do I remove the standard?

![Standard](https://user-images.githubusercontent.com/70098046/124475819-71e1dc80-dda2-11eb-807f-abeef1396fe7.jpg)

<br>

As far as I could tell, nuclear stops playing other songs in the "Favorite Songs" section as soon as the internet is missing. Now I'm wondering whether nuclear writes the songs temporarily to the hard drive every time one of its songs is played in order to be able to play them smoothly or does it write it into the RAM? How exactly does it work?

**Comment by HaiDang666** [comment]
- For the playlist: Currently to create a playlist, we need to add tracks to play queue then save as playlist. Later there will be a button on playlist screen to create an empty playlist (#999)

@nukeop can u help  with the others?

**Comment by dasanchez981** [comment]
OS: MacOs 11.6
Nuclear Version: 0.6.17

Hi, I'm experiencing the same behavior on my taskbar where the Nuclear icon is too big (with respect to the size of the other icons).

Could someone break this issue off into a separate issue so I could work on it? Also, does anyone have suggestions on how to go about resolving this issue?  I'm a first time open source contributor so any help would be appreciated.

**Comment by nukeop** [comment]
This is because other icons include a padding, and we're using the same icon regardless of the platform.

**Comment by dasanchez981** [comment]
Okay I understand. 

Does that mean this a non issue? Or at least an issue that does not have high priority?

**Comment by nukeop** [comment]
It doesn't bother me, but if you want to fix that then go ahead.

**Comment by dasanchez981** [comment]
Yes I can take that on. Any suggestions on how to go about resolving that issue? Would I just to need crop the image to have padding and then somehow choose this image based on the platform (ie. macos only)?

On a different note: 

I understand the issue reported above (in the second video) regarding adding a song to a playlist when there is no existing playlists. I also understand that since this issue was reported, there has been a new feature implemented to create and name an empty playlist from the playlists menu. 

Does it make sense to try to reuse this functionality to address the original concern raised in this issue? For example, let's say a user has no playlists created. If the user searches for a song and then tries to add that song to a playlist, should the user be prompted to create a playlist "on the fly"? (ie. create a new empty playlist and then add the selected song)

**Comment by nukeop** [comment]
You'd need to research how it's done on Mac, maybe adding a padding manually is enough.

There is a way to create empty playlists now, so that second point no longer stands. While we could add the functionality you're suggesting, I'd like to prevent the context menu for tracks from having too many options to be readable, so let's keep it the way it is now.

**Comment by dasanchez981** [comment]
Okay I'll look into how this might be done on a mac.

That makes sense. Thanks for considering.

**Comment by nukeop** [comment]
SQLite is now bundled correctly.
