### ISSUE TITLE
Nuclear gets stuck in an empty dark blue window when trying to play a playlist

### ISSUE THREAD

**Issue by Kripta-Studios** [nukeop/nuclear#1088]
**Platform:** Windows 10

**Nuclear version:** 0.6.16 and 0.6.17

**Description of the issue:** If I import I playlist from a JSON file or I create a playlist from scratch and then I press the big pink botton that says play, then nuclear shows this screen:
![image](https://user-images.githubusercontent.com/68393696/140621214-87fd17a6-70f4-421d-9eef-88ec2e554dca.png)
I don't know where the logs of Nucler are stored, so I can't send the logs.
I tried to reproduce a different playlist in the two last releases, and both get stucked only when I try to reproduce any playlist.
Thank you in advance for the help.

**Comment by nukeop** [comment]
Can you attach the playlist you were trying to play?

**Comment by Kripta-Studios** [comment]
I tested with random playlist like:
[Nueva lista de reproducción - copia.TXT](https://github.com/nukeop/nuclear/files/7491121/Nueva.lista.de.reproduccion.-.copia.TXT)
[playlist test 1 - copia.TXT](https://github.com/nukeop/nuclear/files/7491122/playlist.test.1.-.copia.TXT)

**Comment by Kripta-Studios** [comment]
In Windows 11 happens too, the Nuclear version used is: 0.6.17

![](https://cdn.discordapp.com/attachments/820755276516556820/906626576609869874/unknown.png)

**Comment by MarcusDavanco** [comment]
Same here:
![image](https://user-images.githubusercontent.com/4138199/146519464-1f6e4981-cb79-4563-b20a-202a5d69b43a.png)
![image](https://user-images.githubusercontent.com/4138199/146519505-8e498ad7-3a56-4298-9b3a-faa25623717a.png)

**Comment by NightFireGT** [comment]
https://user-images.githubusercontent.com/97752005/149553778-2755e4ae-2377-405c-91aa-bc39301309d9.mp4
[nuclear-error.log](https://github.com/nukeop/nuclear/files/7872000/nuclear-error.log)

I've tried this on 0.6.13 where the playlist is incompatible, and 0.6.15 and 0.6.17 where it ends up in a blank screen. This happens when you try to play or add any song from the playlist to the queue as well, and I couldn't reload the app afterwards for some reason.

**Comment by nukeop** [comment]
Should be gone now
