### ISSUE TITLE
"Display Track Duration Over the Seekbar" setting doesn't work.

### ISSUE THREAD

**Issue by JFMugen** [nukeop/nuclear#1095]
**Platform:*Windows*

**Nuclear version:*v0.6.17*

**Description of the issue:*"Display Track Duration Over the Seekbar" setting doesn't work. Duration is always there.*

![image](https://user-images.githubusercontent.com/61559703/141806888-4ce1242d-b635-4e5c-acd5-6c845ef596b0.png)

**Comment by nukeop** [comment]
2 things are required to fix this:
- Write a test
- In https://github.com/nukeop/nuclear/blob/6a99b3f85042f170de840d3e9b9381d8cd5fd84b/packages/app/app/containers/PlayerBarContainer/index.tsx, the `renderTrackDuration` needs to take its value from the appropriate setting (`trackDuration`) instead of being always true

**Comment by Yahyakiani** [comment]
@nukeop Could I have this issue ? 1 more thing though is there any reference test component that I could use as reference on what kind of tests to write for this container ?

**Comment by Yahyakiani** [comment]
@nukeop  You can close this issue I believe.Its been merged
