### ISSUE TITLE
Nuclear is too inconsistent, it stops playing after few songs most of the time

### ISSUE THREAD

**Issue by JFMugen** [nukeop/nuclear#1108]
**Platform: *Win 10*

**Nuclear version: *0.6.17*

**Description of the issue: *Sometimes it can't find the next song, sometimes it finds but decide to stop for a reason (sometimes it does that even for first song after I said "play now"), and sometimes autoradio stops searching a new song. It is quite rare to listen songs more than half hour.*

I would be happy to provide a log etc. if there is any.

**Comment by JFMugen** [comment]
For example; 

![image](https://user-images.githubusercontent.com/61559703/145013177-4a905de9-7665-46d7-a2b1-e4a6d887200d.png)

It just stops here. It plays the next song if I click manually, but doesn't do that automatically.

**Comment by Venryx** [comment]
I get inconsistent playback as well, with my playlists just failing to progress sometimes. Granted, it's possible that some of my songs are just in a format Nuclear can't play and/or it is a bug that has since been fixed (I have not updated Nuclear in a long time).

I will try to provide more details sometime in the future. (and with a more recent version of Nuclear)

Despite the playback unreliability, I still use Nuclear as my main music player, because of how easy it is to create custom plugins for it. (The most important feature being the addition of a "weight-based playlists" feature -- which I've wanted in music players for so long, but have only been able to achieve since I made [a custom nuclear plugin](https://github.com/Venryx/nuclear-vplugin) for it. That Nuclear plugins can access everything about the player, and the full-fledged NodeJS environment, makes them very powerful, and a pleasure to add arbitrary features with. Granted, the API could be expanded some to make certain things even easier, haha.)

**Comment by nukeop** [comment]
That's awesome, I feel the plugins feature is kind of underutilized, maybe because there's no place to publish/discover existing ones, but I'm very happy that you find it useful. It makes me really proud that you find it good enough to be your daily driver.

I've got this problem on my radar after other more severe problems that interrupt playback (I think interruptions should be the highest priority since I often just load a long playlist and let it play in the background while I do other stuff, and it pisses me off when I have to come back to the computer to resume it).

**Comment by JFMugen** [comment]
@Venryx I don't use Nuclear for my offline library (I hardly have any offline library at all tbh) so the reason is definitely not file format. I loved your pluging tho, very nice idea imo. 

@nukeop Exactly! This is how I listen as well, I just want to click play and then forget for hours. This issue's point is exactly this. And I think it should be the highest priority as well.

**Comment by MiguelAMLucero** [comment]
I' getting a similar error, I'm running on mac the 0.6.17 version and I tried to listen to an album from bandcamp, but after a few songs the audio is a random song, but the player says it's one from the album I was listening to. it's very annoying

**Comment by JFMugen** [comment]
> I've got this problem on my radar after other more severe problems that interrupt playback (I think interruptions should be the highest priority since I often just load a long playlist and let it play in the background while I do other stuff, and it pisses me off when I have to come back to the computer to resume it).

I just tried the nightly built and looks like this problem is still here and maybe it even got worse? I couldn't past 3 songs without a break yet :/ 

By the way, I am not sure but looks like internet speed doesn't help as well. It broke almost every song while I was downloading something from Steam (so it sucks the whole bandwidth).

**Comment by nukeop** [comment]
I've reworked how streams are fetched recently and I've enjoyed listening for hours without a single interruption now. If it still occurs for you, please reopen or make a new issue.
