### ISSUE TITLE
[Feature Request] Streaming from Spotify, Tidal and Torrent

### ISSUE THREAD

**Issue by d3417** [nukeop/nuclear#1118]
Why do not add this features? **Just open a Free Spotify Account, integrate into Nuclear App, eventually block ads (Premium Style) and about Tidal just make a Login function for Subscribed Users and the work is ended, about Torrents i don't know, but so much services uses torrent as media source for streaming it like PopcornTime, Stremio etcetera for Tv Series and Films, why not for Music**?

And a **Google Grabber for music hosted in external websites**? (Like www.rupsy.ru that host a lot of PsyTrance)

It's only a list of ideas, but, if at least one of these is achieved I will be more happy to use your player. :-)

-Denis Sossich

**Comment by d3417** [comment]
And BandCamp!

**Comment by nukeop** [comment]
Bandcamp is already integrated, you can search in it and use it as a streaming source.

As for Spotify, this is probably one of the most obvious things to do, and I investigated this possibility thoroughly, but it's definitely not possible. To use Spotify for streaming, you not only have to use their SDK, and embed their entire player, you also need a registered app to use it. Obviously Nuclear would be banned for ToS violation within 10s of going live. You can't just share a single free account with thousands of users either.

The last guy who tried making torrenting music easier got a $3 million dollar lawsuit: https://torrentfreak.com/riaa-and-aurous-settle-piracy-lawsuit-for-3-million-151209/

Even if I were inclined to ignore the possible life ruining legal issues, it's still not that easy, since you'd need a tracker that lets you stream individual songs randomly and on demand.

**Comment by JFMugen** [comment]
>Even if I were inclined to ignore the possible life ruining legal issues

Don't do that ^^

**Comment by VihagChaturvedi** [comment]
Alternatively, is it possible to embed Spotify in Nuclear itself, while requesting users to get log in with their own spotify account?

I am not 100% on the legality for this, but I have done smth similar before.

Essentially since firefox allows me to "install as an app" option on android, which essentially loads in all configs and extensions into a sandbox of sorts.

I used this to play spotify without ads using Ublock Origin on my phone, while keeping all features except shuffle.

I would be perfectly fine with it even if I didn't have the option to download music.

**Comment by nukeop** [comment]
If you mean embedding an iframe, it would probably work, but it would not integrate well with the rest of the player. Using Spotify SDK carries all the downsides I described above.

**Comment by VihagChaturvedi** [comment]
> If you mean embedding an iframe, it would probably work, but it would not integrate well with the rest of the player. Using Spotify SDK carries all the downsides I described above.

Would it not be possible to read the source and scrape it to give results accordingly? 

Or is that itself violating ToS?

**Comment by nukeop** [comment]
It's locked down very tightly. You can't access the streams directly, they're encrypted. So it's not possible to just play them without using the sdk. The page can be scraped and that's what's used to import Spotify playlists.

**Comment by VihagChaturvedi** [comment]
> It's locked down very tightly. You can't access the streams directly, they're encrypted. So it's not possible to just play them without using the sdk. The page can be scraped and that's what's used to import Spotify playlists.

I see.

Sounds like a horrible idea but hear me out, will it be feasible to embed a browser in Nuclear for this?

Obvious disadvantages include increased ram usage, unecessary complexity and substantially increased download size.

Advantages include, a spotify player, integration of it with other services and a complete experience for Nuclear.

**Comment by JFMugen** [comment]
> Advantages include, a spotify player, integration of it with other services by scraping source from the embeded browser and a complete experience for Nuclear.

If I want to use Spotify that much, I would download Spotify instead. I think it is overall unnecessary, and it doesn't make sense to bundle with Nuclear.

**Comment by VihagChaturvedi** [comment]
> > Advantages include, a spotify player, integration of it with other services by scraping source from the embeded browser and a complete experience for Nuclear.
> 
> If I want to use Spotify that much, I would download Spotify instead. I think it is overall unnecessary, and it doesn't make sense to bundle with Nuclear.

I do feel like I went a _bit_ unreasonably far with that one

Aprreciate the response!
