### ISSUE TITLE
Wrong song is playing

### ISSUE THREAD

**Issue by uqlel** [nukeop/nuclear#1221]
**Platform:**
Windows 11
**Nuclear version:**
[2dd909](https://github.com/nukeop/nuclear/releases/tag/2dd909)
**Description of the issue:**
I have selected artist's profile and have selected one of his tracks. When I play it it plays the wrong track also his, but it has title of another song. 
Better explain:
I select artist and play one of his songs, but I hear his another song. With other 5 songs its good.

**Comment by nukeop** [comment]
Can you give us more info? What song/artist and which streaming provider you're using?

**Comment by nukeop** [comment]
I checked these examples and in both cases the correct song plays. Since the original post, I have created heuristics for youtube which should improve the accuracy.

**Comment by DrTexx** [comment]
It is indeed playing the right song for me now, thank you! :)

I'll drop another comment if I encounter any other mismatches :+1:

**Comment by Vinesauced** [comment]
Hello, I was about to post a new issue when I saw this one closed.
With the latest version of Nuclear, I am having a similar issue, except it never plays the correct song no matter which provider I choose. 
I want to listen to [Mount Saint Helens is About to Blow Up](https://www.youtube.com/watch?v=elizAugXVcI) but it gets the [Genius lyrics review](https://www.youtube.com/watch?v=80HRXgEeXts) of the song instead of the actual song, and this happens for nearly every provider except for Bandcamp and Soundcloud that fetch the Jazz cover of the song.
The only explanation that comes off the top of my head would be that the Genius lyrics video is closely titled to the original song. The only way to consistently play the song is to search the link straight from Youtube and play the result.

I agree to what @DrTexx said, I would enjoy a manual override feature where you can input the correct URL if for whatever reason the different providers are unable to get the correct result, and this feature could also be useful for alternative sources, like if I wanted to play a song straight from billwurtz.com, but I don't know how doable this would be.

**Comment by nukeop** [comment]
I'm reopening this. I'll take a look at what songs are fetched for these search terms and tune the heuristics. Keep in mind that the original might not be available on Soundscloud/Bandcamp.

**Comment by DrTexx** [comment]
Perhaps it would help to add an option to the menu that appears when you click a track to report a mismatch from nuclear?

Even if it's just a preference or only shows up when developer mode is enabled, it might help us more easily provide you data to improve the heuristics :)

I would still very much like to be able to manually override matches locally if I can (even if it's just to paste a YouTube/Spotify/etc. link), however perhaps in-app mismatch reports are a nice middle-ground ⚖️

**Comment by nukeop** [comment]
> Perhaps it would help to add an option to the menu that appears when you click a track to report a mismatch from nuclear?

Report it where? I guess I could keep a running thread in an issue on Github so users can report those.

**Comment by DrTexx** [comment]
Not quite sure, I suppose the implementation would be up to you.

A few idea of the top of my head
- Trello board just for mismatches
    - (providing you can allow people to submit mismatches without deleting other people's)
- An email address for just mismatch reports
- A Twitter account to report mismatches to
- A form through some service that lets people report anonymously (I know this exists but I don't know the name of one off the top of my head)

Of the ones I just thought up, I'd probably go with email. Only potential concern there is user privacy since you'll know their emails, but that's not my call to make if it's make or break.

**Comment by DrTexx** [comment]
Also I would avoid GitHub because if you point people here to create a comment in a thread, they may create an all new issue instead (unless you add an issue template for mismatches maybe)

**Comment by UltraBlackLinux** [comment]
I have a similar issue: There is an artist (HOME) that has music which has the same title as just non-music (Yoga apparently) content in the "Resting State" Playlist. Easily visible by the fact that they are sometimes 30 min long.

The issue only appears when fetching the music, not when looking at the playlist: 
![screenshot-20220510-165526](https://user-images.githubusercontent.com/62404294/167658644-c76cdbab-272c-47de-8673-9187dac2ad51.png)

**Comment by carmona** [comment]
I just ran into the same issue with another artist. Win11 + nuclear @ `eac584`

> Report it where? I guess I could keep a running thread in an issue on Github so users can report those.

@nukeop if you want to keep things inside github issues, maybe have a button in each song/album/artist that will send a comment through Github's API to a fixed issue. I don't think most users would go through the trouble of creating a GH account just to mention one mismatched song.

Also: how about showing a list of possible correct matches so the user can suggest it instead?

**Comment by nukeop** [comment]
Showing a dropdown with all possible choices is planned in the future so you'll be able to select a different stream yourself.

**Comment by kohend** [comment]
Trying to play "What Else Can I Do?" from Encanto soundtrack gives me this: http://www.youtube.com/watch?v=mV6iFCPm_60

**Comment by nukeop** [comment]
@kohend Did you try switching streams? Or is your song not present on the list?

**Comment by nukeop** [comment]
BTW, I think I can close this issue as selecting streams is already implemented.

**Comment by kohend** [comment]
It's not in the selection options at all despite the song being on youtube (with the singers' names instead of "various artists")
