### ISSUE TITLE
bandcamp source doesnt work

### ISSUE THREAD

**Issue by anonimQwerty** [nukeop/nuclear#1236]
**Platform:**
windows 11 pro

**Nuclear version:**
2dd909 
**Description of the issue:**

when I search songs via bandcamp it finds it but doesn't play

**Comment by nukeop** [comment]
Thanks for reporting. It's wonky, because the scraper (https://github.com/masterT/bandcamp-scraper) doesn't always find individual tracks, even if they're listed on the album. Do you have any examples I could look at?

**Comment by anonimQwerty** [comment]
https://user-images.githubusercontent.com/61067633/160890367-d8c6057b-70a0-4a2a-9952-7b3dfdd98c08.mp4

**Comment by WolfangAukang** [comment]
@anonimQwerty what if you change your metadata provider to Bandcamp? I ask this because I had this issue using Discogs, but after changing it to Bandcamp, it worked.

I'm having another kind of issue compared to the video posted above.

**Comment by anonimQwerty** [comment]
> @anonimQwerty what if you change your metadata provider to Bandcamp? I ask this because I had this issue using Discogs, but after changing it to Bandcamp, it worked.

How to change metadata provider?

**Comment by nukeop** [comment]
You can switch it using the dropdown next to the search input box.

**Comment by WolfangAukang** [comment]
I'm having a slightly different issue regarding Bandcamp though. There are some albums that are showing an error message when I click them:

![image](https://user-images.githubusercontent.com/8378365/164064113-249aabc9-367a-45d0-82db-4872655440cb.png)

Not sure what would be the issue with the album, because [it looks fully available](https://wearebrutus.bandcamp.com/album/nest) on Bandcamp

**Comment by nukeop** [comment]
When you look up an album in Nuclear, we do essentially the same thing as searching directly on the Bandcamp website to find it: https://bandcamp.com/search?q=brutus+nest&item_type=a&from=results

For whatever reason, albums that are otherwise available, don't always show up in the results, causing this error. Bandcamp has no API so we're forced to scrape the site.

**Comment by WolfangAukang** [comment]
> For whatever reason, albums that are otherwise available, don't always show up in the results, causing this error. Bandcamp has no API so we're forced to scrape the site.

Got it, that's completely reasonable

**Comment by nukeop** [comment]
This has been recently improved by a contributor and is available in the new release.
