### ISSUE TITLE
Ability to specify the location of the Local Library base

### ISSUE THREAD

**Issue by Korb** [nukeop/nuclear#1313]
In the current version of the application for Microsoft Windows, after scanning the folder with audio files, the application folder still contains only the nuclear-3f9007.exe file. I believe the database is located somewhere in the system user preferences folder (eg %APPDATA%\nuclear). I would prefer to tell the application myself to use a folder for such data, or place the settings and the database itself directly in the application folder.

Can this be done with a separate setting?

**Comment by nukeop** [comment]
The config is stored there because we use this library: https://www.npmjs.com/package/electron-store
Which in turn uses this API: https://www.electronjs.org/docs/latest/api/app#appgetpathname
This is a standard practice and common convention to store the config separately and I'm not planning to change this.

**Comment by Korb** [comment]
Bypass: create a symbolic link `nuclear` in the `%APPDATA%` to dir, in which you want to place the application settings and the media text base. In Microsoft Windows 10.0.19045.4651, it works properly.
