### ISSUE TITLE
Nuclear & OBS

### ISSUE THREAD

**Issue by Ahebah** [nukeop/nuclear#1325]
**Platform:**

Windows 10 - Latest Build

**Nuclear version:**

3f9007

**Description of the issue:**

I have been trying to use Nuclear as an alternative to Spotify for my stream music. But when OBS I guess "hooks" in to Nuclear it seems to stop working when you play a next song, alternatively if you make a playlist, when it goes to play the next track, it just freezes.

**Comment by Bradley-Basik** [comment]
If you use window capture to capture nuclear, it gets the audio without causing the songs to freeze. When setting up the window capture, select nuclear and in "Window Match Priority" make sure "Match title, otherwise find window of same executable" is selected, as otherwise obs will not capture the next song since the title of the window will change.

You can crop the window so you can only show the title of the song somewhere in your scene, or just make it invisible/order it to the bottom so it does not display at all.

Hope this helps
