### ISSUE TITLE
Nuclear plays a different track than what is shown

### ISSUE THREAD

**Issue by unfa** [nukeop/nuclear#1332]
**Platform:**

Windows 10

**Nuclear version:**

Newest release

**Description of the issue:**

Nuclear correctly fetches album tracklist, but then for some tracks plays audio for completely different song.
My experiences come from Savant's album "Krang".

Here the metadata says it's playing a track "Firestarter" when in reality it's playing "Wildstyle". The UI even confirms that:
![image](https://user-images.githubusercontent.com/491704/194858212-4bfbc0ed-a5e7-48cd-a247-67c22a93bcf6.png)

Simiarly for track "Kingdom" it plays "Rare Mix" instead:
![image](https://user-images.githubusercontent.com/491704/194858550-58d68e4b-8f88-4006-853d-84a340a86a8d.png)

**Comment by nukeop** [comment]
Ok, I figured it out. The algorithm ranks the video called "Savant - Wildstyle" 1st, even though there's a video called "Firestarter" among the search results (which is ranked 2nd). This is because the first video contains the artist name, which raises its score. The solution would be to raise the score depending on the channel name. I'm going to implement this now.

**Comment by nukeop** [comment]
I made it raise the score by 200 if the channel name matches the artist name verbatim, and the track name matches the vidoe title verbatim. This should handle your case, I used it in a test to make sure.
