### ISSUE TITLE
System media control (MPRIS) not working when using the Flatpak version

### ISSUE THREAD

**Issue by sith-on-mars** [nukeop/nuclear#1435]
**Platform:**: OpenSUSE MicroOS Gnome

**Nuclear version:**: fd06a3

**Description of the issue:**:  MPRIS doesn't work when using the Flatpak version, despite the fact that it seems to work with standard package version, according to [issue 1123](https://github.com/nukeop/nuclear/issues/1123). I think there are a lot of Flatpak apps that support MPRIS, it would be super if the developers could implement this.

**Comment by nukeop** [comment]
Hi, MPRIS works with most of the other packages. I never cared to fix it in flatpak because there's already a lot of different installation options and flatpak makes many things that should be easy a huge pain. But if anyone knows how to do it, I'll gladly merge a fix.

**Comment by will-ca** [comment]
@nukeop **TL;DR**: I *think* you need `"--talk-name=org.mpris.MediaPlayer2.nuclear"`. But I can't actually test it because all playback in Nuclear is currently broken for me, so I'll hold off on submitting a PR.

---

Flatpak makes many things that should be easy a huge pain, *if* you don't know how to do them, which obviously most of us don't (Because why would we? It was working fine before). Idk. I think they really need better docs or examples or something.

I assume it's an issue of exposing the right DBUS channel.

For reference, this is what I had to do in my own application to get **system tray icon support** (not MPRIS— Reminds me I should probably do that, actually):

```YAML
    "finish-args": [
        "--talk-name=org.freedesktop.Notifications",
        "--talk-name=org.kde.StatusNotifierWatcher"
    ]
```

IIRC I also needed to add a similar override for Nuclear to get it to show in the system tray.

I think this is the relevant spec for MPRIS:

https://specifications.freedesktop.org/mpris-spec/latest/

IIRC, By default in Flatpak ["an app can only own [and access] its own name on the bus"](https://docs.flatpak.org/en/latest/sandbox-permissions.html).

So I believe for Nuclear, that would be `org.js.nuclear.Nuclear`:

https://github.com/nukeop/nuclear/blob/f9effe4c5d39935449a9c58c7a3d26d682495a2b/flatpak/org.js.nuclear.Nuclear.json#L2

(IIRC They also allow hyphenated qualifiers after the end of the full app ID, or something like that.)

For MPRIS, I think something like:

```JSON
"--talk-name=org.mpris.MediaPlayer2"
```
AND/OR

```JSON
"--talk-name=org.mpris.MediaPlayer2.*"
```

AND/OR

```JSON
"--talk-name=org.mpris.MediaPlayer2.<NameOfWhateverNuclearRegistersItselfAs>"
```

…Should do it.

I would like to test these for you to figure out exactly which it is, but unfortunately, both online and local playback in Nuclear are currently broken for me (#1438, #1439). It may also be [`--system-talk-name`, rather than `--talk-name`](https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html).

…However, in the course of summarizing this, I accidentally discovered that I can temporarily add an override to enable all busses, and then inspect which one is active:

![image](https://user-images.githubusercontent.com/37680486/230677092-d25eba04-a7d9-4f1e-8c51-0dc2d1ddce14.png)

It appears that `org.js.nuclear.Nuclear.json` will require `"--talk-name=org.mpris.MediaPlayer2.nuclear"`. But maybe try the other options, or look at the spec more carefully than I skimmed it, if that doesn't work.

**Comment by BinaryGenius** [comment]
Adding `org.mpris.MediaPlayer2.nuclear` worked on my system now system media controls are working flawlessly. Hopefully nukeop or someone else can merge this in with the flatpak by default. If anyone wants to fix the issue you can use flatseal and under the "Owns" section under the "Session Bus" section put `org.mpris.MediaPlayer2.nuclear` and media controls should work! If you install Freetube you can see that they use this exact solution. Nice find will-ca thanks for the fix.
![Screenshot from 2023-09-17 20-48-04](https://github.com/nukeop/nuclear/assets/105467963/b6977714-356f-47c2-b272-63ceb058e04b)
Aforementioned freetube is down below this is an unchanged install.
![Screenshot from 2023-09-17 20-50-30](https://github.com/nukeop/nuclear/assets/105467963/cfdc43e6-a6f2-4402-a764-4e8384011530)

**Comment by BinaryGenius** [comment]
> Hi, MPRIS works with most of the other packages. I never cared to fix it in flatpak because there's already a lot of different installation options and flatpak makes many things that should be easy a huge pain. But if anyone knows how to do it, I'll gladly merge a fix.

I don't think it's too hard but do I think it has a learning curve? Absolutely. But then again I'm not a developer. I very much appreciate the hard work you've put into the project but I think flatpaks should take your top priority. They offer a form of sandboxing that is basically unheard of among linux applications, the installs are really small and easily manageable, and flatpaks are of course distro agnostic. Considering you use electron I'm sure you are well aware of the benefits distro agnostic packing schemes bring to the table. More people will have access to your app too so why not use flatpak. I think at the very least we could remove appimages. If it was up to me I'd have a .exe .dmg and a flatpak but I'd like to know what you think.

**Comment by nukeop** [comment]
BTW, check out the release statistics: https://tooomm.github.io/github-release-stats/?username=nukeop&repository=nuclear

Appimages are one of the most popular binaries. I don't track installation or downloads elsewhere so I don't have any up to date metrics but Appimages are the most painless distro-agnostic way to install Nuclear, I certainly don't want to discontinue them.

**Comment by BinaryGenius** [comment]
> The Flatpak config is here: https://github.com/flathub/org.js.nuclear.Nuclear
> 
> Do you think your solution can be permanently added to it?

I'll try but I have limited experience with this. I'm assuming I can use Freetube's flatpak config as a reference since they used the same solution.

**Comment by nukeop** [comment]
I merged the above PR.
