### ISSUE TITLE
Javascript error - uncaught exception error - pops up before launch

### ISSUE THREAD

**Issue by HyperSmartian** [nukeop/nuclear#1502]
Windows 10 22h2

Nuclear 0.6.30

![image](https://github.com/nukeop/nuclear/assets/106574944/0487d635-b25c-4947-8b8c-97997713f0be)
The above image describes the error that pops up, Once i click 'ok' it closes and the player opens. Might be a problem with my pc, please look into it and let me know, Thanks in advance!

**Comment by nukeop** [comment]
Do you think nuclear has access to the downloads folder?

**Comment by HyperSmartian** [comment]
Yes I suppose it does, run it with administrator privileges on Windows 10

**Comment by omaquaire** [comment]
Hello,

I just wanted to back this issue, since I have the same.
I'd like to add that at first I used the version 0.6.30 normally, and at some point this kind of issue started.

Speaking of change, at least I did not notice any conscious (as opposed to a system update or so)
I am pretty sure it must be something very stupid, like a wrongly set variable since it is trying to create an impossible directory.

I was wondering if there was a way to reset my whole profile, see if this would help.
At least I tried, uninstall and reinstall the application to no avail.

Cheers.

**Comment by nukeop** [comment]
> I was wondering if there was a way to reset my whole profile, see if this would help.
You can try deleting your config. It should be located in `~/.config`, or %APPDATA% on Windows.

**Comment by HyperSmartian** [comment]
Ok, I'll check it out.

**Comment by omaquaire** [comment]
Hello there,

Just removed %appdata%/nuclear as advised.
Actually the application is now starting without any failure or annoying message.

Just for the sake, I did a backup of that directory before deletion, and I am quite amazed to see it is weighing 256 MB.
Not sure why, but I could find a whole bunch 1MB of files in the cache section.

Should you want some more details, feel free to contact me.
