### ISSUE TITLE
Mouse Back Button does not do anything

### ISSUE THREAD

**Issue by hollow-owl** [nukeop/nuclear#1565]
**Platform:** Arch Linux 6.7.6-arch1-2

**Nuclear version:** 0.6.30

**Description of the issue:**
Using the back button on the mouse does not do anything. I would have expected it to do the same thing as the gui back button. Same for the forwards button.

Steps:
1. Have a mouse with a forward and back button
2. Open Nuclear and start navigating around the UI
3. Click mouse back button (doesn't do anything)
4. Click the gui back button (does go back to the last place you were)
5. Do the same for the forwards button

**Comment by L30R** [comment]
Hello i'm a learning dev and this implementation seems interesting, for adding purpose, i would like to know in what file this implementation would need to be in ?

**Comment by nukeop** [comment]
Somewhere in the `main` package. For example, we handle many different events here: https://github.com/nukeop/nuclear/blob/master/packages/main/src/main.ts

However, since it requires handling different events per platform, it may also be a part of platform-specific services, which can be found here as `@linux`, `@mac` and `@windows`: https://github.com/nukeop/nuclear/tree/master/packages/main/src/services

**Comment by L30R** [comment]
I did work on this but was a little too slow, so i tried to adapt the  part from the "if" into "switch" from the PR as nuki-chan said. I don't know if i did thing correctly or if this was necessary, i do apologies if this is not.  The PR is #1567.

**Comment by nukeop** [comment]
Hm, I'd like to merge both of your PRs to acknowledge your contributions. And in fact both are necessary, because yours doesn't include @hollow-owl 's code. If I merge his first, then your PR will cause a merge conflict. You could try pulling changes from his fork first, then both your commits will be included, and merging your PR will effectively merge both PRs.
