### ISSUE TITLE
Miniplayer bugged controls

### ISSUE THREAD

**Issue by sicin** [nukeop/nuclear#1592]
**Platform: Ubuntu 22.04**

**Nuclear version: 0.6.30**

**Description of the issue: Miniplayer lacks volume control and both "autoradio" and "miniplayer" (I guess it shouldn't even be there) controls are unclickable. Looks like the fix for #1396  didn't resolve the issue.**

**Comment by nukeop** [comment]
I can confirm. In this case the miniplayer button should return Nuclear to normal mode.

**Comment by CarlosBor** [comment]
Hey there,

The good news are that the miniplayer button _does_ return the player to its normal mode, The problem is that another div is covering the buttons, rendering them unclickable, as a matter of fact the shuffle button is only half clickable.

![image](https://github.com/nukeop/nuclear/assets/48533334/4e46fdd4-e90a-4512-b1cc-101a773fcc4c)

May I take a shot at this? It should just be a small css tweak

**Comment by nukeop** [comment]
Sure, if you can figure it out that would be nice.
