### ISSUE TITLE
Add importing of 3rd party playlists

### ISSUE THREAD

**Issue by ivyjsgit** [nukeop/nuclear#199]
It would be a nice feature to be able to import playlists from other sources such as Youtube or Spotify, or some other service so that you don't have to remake playlists from scratch.

**Comment by trekiteasy** [comment]
As of today, it is possible to put a Youtube playlist url in the search and the 100 first songs of the playlist will appear in search results.
- Limitation to 100 first tracks for now
- Only playlist urls work (no single track url)
=> it is kind of a hidden feature so we have to think how this should be integrated to be usable.

**Comment by nukeop** [comment]
Spotify doesn't allow you to export or share playlists, by design. This is one of the reasons this program was created... 

Maybe there is a way to extract them if you log into Spotify through Nuclear.

**Comment by nukeop** [comment]
I looked around and it turns out that you can use the web API to export playlists but you need to log in first. There's a node.js wrapper for that, so we're covered on that front. I'll need a dummy spotify account for testing, and I might be able to implement that, provided we don't get banned/sued/blocked by spotify.

**Comment by nukeop** [comment]
Added by @HaiDang666 in the form of json file import
