### ISSUE TITLE
Nuclear public API

### ISSUE THREAD

**Issue by jamesrweb** [nukeop/nuclear#252]
# Nuclear public API layer creation

Since nuclear is already collating multiple sources to generate its music library, why not create a separate `nukeop/nuclear/api` repository or something of the like and host it on, for example: `https://api.nuclear.gumblert.tech`?

## Recommendations

Perhaps create an organisation on Github called nuclear and move the source code of nuclear to `nuclear/nuclear` to be a bit cleaner and then when generating the API repo it can sit inside `nuclear/api`.

Further to this, perhaps a new domain of `https://nuclear.io/` or something of the like could be cleaner and then the API calls, of course, would go to `https://api.nuclear.io/`, etc.

### /artists - [GET]

returns no resource or a resource of shape:

```javascript
{
  data: Array<Artist>
}
```

> If implemented, limited to 100 for the search term 'a' as an example of a sane default.

#### /artists/:id - [GET]

returns an resource of shape:

```javascript
{
  data: Artist = {}
}
```

### /albums - [GET]

returns no resource or a resource of shape:

```javascript
{
  data: Array<Album>
}
```

> If implemented, limited to 100 for the search term 'a' as an example of a sane default.

#### /albums/:id - [GET]

returns an resource of shape:

```javascript
{
  data: Album = {}
}
```

### /songs - [GET]

returns no resource or a resource of shape:

```javascript
{
  data: Array<Song>
}
```

> If implemented, limited to 100 for the search term 'a' as an example of a sane default.

#### /songs/:id - [GET]

returns an resource of shape:

```javascript
{
  data: Song = {}
}
```

### /search?q=:query - [GET]

This would work akin to the current search, returning a resource of shape:

```javascript
{
  songs: Array<Song>,
  albums: Array<Album>,
  artists: Array<Artist>
}
```

## Why would this be useful?

First of all, from my knowledge of poking around the application and a high-level code dive, everything is super tightly coupled, this is problematic for scalability and patchability in my view, thus splitting the API layer away from the app means issues like certificate regeneration happen in one place and one place is responsible for it, not like currently where API issues affect the app itself as can be seen in #145 for example.

Secondly and for me the most interesting, it would allow others to build on top of the nuclear platform. All the hard work of collating from multiple sources is a massive selling point. I think this could be really nice to have for all involved, especially if it was open source.

Thirdly, this would allow iOS and Android app development with ease. Add a skin, add API calls and boom, the job is done. This decoupling of frontend and API would be really nice for this multi-platform use case for sure.

## How could this be accomplished?

I personally would use either `NodeJS + Express` or `Python + Flask` to generate the API but as you well know, anything is possible to use, go crazy, use `Go` or `C#`, better yet, let the community decide.

### API commentary

If an API was to be generated, I would also add `GraphQL` endpoints in the process of the APIs development cycle and add it as a 'definition of done' for each endpoint generated. Having both RESTful endpoints and GraphQL endpoints would be hugely awesome considering the benefits of each and gives developers a choice on which to use based on the project, platform, etc.

Of course, also, these endpoints could be extended out with the public API to have `POST`, `PUT` and `DELETE` endpoints should that be a useful internal requirement but obviously you wouldn't want to expose that in a public API for this kind of app or... would you? I don't know. Either way, it is, of course, something to think about alongside other relevant items of note.

### Splitting of the application

Of course, you could also add a further service under, as an example: `nuclear/database`.

This would, if not already existing, store a song, artist or album config in a normalised manner akin to the same interfaces involved in the API service outlined here. This would require fewer requests to external API services by storing response data in a permanent backend. This would also be supported, of course by caching on the HTTP layer.

Further to this, the backend becomes nonexistent, you would effectively have 3-5 repositories and multiple application build possibilities:

- `nuclear/desktop-frontend` - web/desktop skin
- `nuclear/ios-frontend` - iOS skin
- `nuclear/android-frontend` - Android skin
- `nuclear/api` - API layer config
- `nuclear/database` - database config

I say 3-5 because maybe there is a way to turn the 3 frontend repositories into 1 `nuclear/frontend`, this is recommendable if the codebase doesn't get convoluted in the long run with platform-specific junk.

## Closing thoughts

I hope this was a good first issue to raise on the repository with relevant information included for everyone to chew over.

I would appreciate feedback and if any issues with the idea or sentiment occurred, please let me know. 

Further to this, if you have any questions, do not hesitate to ask in a comment below for me to elaborate on any area outlined above or that you feel was missed out.

**Comment by nukeop** [comment]
While this would certainly open up a whole world of new possibilities, and I've already considered something like this, I'm against it. This would add a huge cost of maintaining a server, and cause the whole program to stop working for everyone if the API goes down for any reason. Scaling up to the current number of users might be possible with a cheap $10-20 Digitalocean droplet, but atm developing Nuclear doesn't cost me anything and doesn't come with a responsibility of maintaining a whole separate service for all its users.

Decoupling some functionality and ui elements has already started (nuclear-ui and nuclear-core packages) and I hope maintainability can be improved progressively by going in that direction. 

I'll give your ideas some more thought though.

**Comment by nukeop** [comment]
I considered creating a service for a feature that can't be implemented client-side:
https://github.com/nukeop/nuclear/issues/172

I guess I could entertain the idea of having a service that would handle features that have to be coordinated among many users, and maybe for replicating some of Nuclear's capabilities in a public API, but I will definitely restrict as much functionality to the client instead of delegating it to the server.

**Comment by jamesrweb** [comment]
I would argue that if cost is the biggest concern, there are solutions to that issue. 

I mean the project has a lot of new interest in recent weeks and if it is shown that a concerted effort to better structure and simplify the app has been made, more users would wish to invest in the codebase (code contribution & finance) and consider donating towards the project as can be seen in many other projects, small and large alike, for one avenue option. I for one would be open to this option personally but of course, there are other avenues to consider.

I feel that full decoupling, beginning with the API, is better in the short and long run. 
- The short run because further feature development will only make the decoupling process harder in the long term. 
- The long run because the ability to market the API as a separate product and to also rapidly develop for new platforms become profusely apparent.

This doesn't only go for the API, these points can also be applied to the aforementioned frontend, database, etc.

Further to your point on putting more control on the frontend, personally I would generally avoid this, most frontend shifts cause more performance/accessibility/strong-coupling than is usually ideal in my experience and down the line when you attempt abstraction/decoupling/re-structuring, it usually blows up. Maybe that's just me and my experience to date but just some food for thought I suppose.

I am willing to help out wherever possible also, just as a sidenote, code wise, feature wise, etc. So this isn't just a "here you do this" type thing but a "you do this maybe but if you need help, let me know what, why and how and lets see" type of thing. Does that make sense? I think it does. It is almost 4am so who knows. Either way, I think you get my point.

I wonder what your thoughts are at this time?

**Comment by nukeop** [comment]
When I mention cost, I mean the cost of development and involved labour, not financially. I don't need donations, I have a job, and any software I make as a hobby is free for all as long as they comply with the license. I only put an icon at the bottom of the readme file because somebody REALLY wanted to give me $10.

As for the API, I'm not opposed to the idea of creating it altogether, it's just that I'd rather keep functions that work better when distributed in the client. Decoupling will involve some work but we'd have a more flexible product if we kept the most important functions in a separate library, instead of putting them behind an API. And this way if somebody still feels they want an API, they can make one trivially, using that very library. If we decide to develop for more platforms (and chances are, we will), every platform gets its functionality from the single shared package that's loaded as a dependency, and we just connect the UI to it, which has to be developed separately anyway.

I don't want a single point of failure server that takes everything with it when it goes down. I don't have to monitor anything or wake up at 3AM to restore some cluster somewhere or fix DNS issues or whatever. I have enough of that at work already. There are no problems with scalability, since there's nothing to scale, each user brings their own resources to run this on. And the cpu/memory requirements are very modest anyway (yeah I know it's electron, but the whole program requires less than a single Gmail tab in a browser).

I have some ideas for cool things that will only be possible if there's a server for sharing some data between users, but all of those will always exist as enhancements that will not interfere with any core functionality if they're unavailable. Mpsyt and youtube-dl do their main tasks without any central servers, so we can (and should) too. I also have a feeling that while Youtube's machine mind is fine with users streaming a song once every 5 minutes, it'd ban our ass in an instant if we suddenly started requesting a 100 a minute and proxying them to Nuclear's users.
