### ISSUE TITLE
Support For Local Files

### ISSUE THREAD

**Issue by infosisio** [nukeop/nuclear#272]
When is this coming? Pretty crucial to audiophiles.

**Comment by nukeop** [comment]
Some partial support for MPD is already implemented on my development machine, opening local files is in the pipes for v0.5.0, which means pretty soon. Although, this program will likely be a hard pass for zealous audiophiles.

**Comment by akaleeroy** [comment]
I use foobar2000 with [foo_youtube](https://fy.3dyd.com/home/) and it irks me terribly that when someone send me a nice tune from YouTube I bring it into a Foobar playlist... then at some point I get it as a file, which has to sit in the library on an external 1TB HDD...  Now I have 2 sources for the same entity. Both of which can be broken – the external drive may be disconnected, the machine may not be online, the online service link can get dead. The song is still playable but the system makes me manually fix it.

So this feature should incorporate a fix to this UX problem. Like object storage, one entity, 0 to ∞ sources, metadata accumulates on the entity, _not_ the brittle sources.

I may be preaching to the choir here, apologies for parachuting into the thread.

Also I'd like to note that aggregating YouTube, Soundcloud and Bandcamp makes this an _everything bucket..._ a hard slog ahead.

**Comment by charjac** [comment]
if you want some help for this i would enjoy it.

**Comment by nukeop** [comment]
It would be really really great. I'm not sure how to integrate this feature with the current UI yet. I think we'd need to separate it completely from the current flow, and add it as a new option in the sidebar menu. Then, a local file browser that lives in its own view and lets you add folders to scan. We could use the metadata to order the music instead of sorting it by folder, this would allow us to sort by artist, album, year, etc. If you do choose to implement this, keep me up to date, I really like seeing your progress.

**Comment by charjac** [comment]
its way too calm at work actually :D so i have a lot of time, i can start tomorow. I had exactly the same idea for the implementation.
I will create a new branch in this repo instead of mine, it will be simplier for you to check the progress.

**Comment by nukeop** [comment]
Okay, awesome. You have full access to the repo.

**Comment by charjac** [comment]
Thx, i created a draf pr #301, we could continue the discussion here.
