### ISSUE TITLE
Error when trying to play a playlist

### ISSUE THREAD

**Issue by hibroseph** [nukeop/nuclear#285]
When I save a new playlist and try to play it, nuclear restarts and I get these errors:
![image](https://user-images.githubusercontent.com/28901411/54294216-d85de380-4576-11e9-87c1-e037cccbc9f6.png)
![image](https://user-images.githubusercontent.com/28901411/54294232-e3187880-4576-11e9-8ac4-b832ef075611.png)

Nuclear will restart and run normal again, if I try to play another playlist, I get the same 4 errors and this time nuclear enters into an endless boot cycle showing this screen

![image](https://user-images.githubusercontent.com/28901411/54294535-2672e700-4577-11e9-8861-1f87deaf2d84.png)

This is running the updated (as of march 13th 2019) version of the master branch on Linux Mint

**Comment by nukeop** [comment]
Actually, what you see afterwards is just the default html template without React.

I think the problem here is that the stream URLs are saved in the playlist, but it seems that Youtube deactivates them after a while and they'd need to be refreshed. When you try to play a song with an invalid URL, something crashes.

**Comment by hibroseph** [comment]
so I think I saw that the playlist information is saved in /.config file?

**Comment by nukeop** [comment]
Nevermind, I looked at the error log you attached and the cause of this problem is different, there's a `this.props` in the PlaylistViewContainer that needs to be replaced by `props`. It's because it was switched from a class to a functional component but somebody who did this (maybe me) forgot to change the way the props are supplied. I'll do this in a sec.

**Comment by nukeop** [comment]
Try the dev version, pretty sure this is solved now.

**Comment by nukeop** [comment]
Yeah it was me. I have no idea why I did this, I usually test that everything's working before committing.

**Comment by hibroseph** [comment]
It works now! Thanks!
