### ISSUE TITLE
Thumbs up / Like / Bookmark feature a song

### ISSUE THREAD

**Issue by hibroseph** [nukeop/nuclear#292]
Sometimes there's a song that you might not want to add to a playlist, but you want to bookmark it or like it. This way maybe you could just go to another tab in the application and play all the music that you have liked or thumbs up instead of having to make a playlist and add it to it.

**Comment by nukeop** [comment]
Could be solved similarly to how Spotify handles this...

**Comment by YajanaRao** [comment]
@nukeop Shall I work on this feature ?

**Comment by YajanaRao** [comment]
@nukeop Shall I work on this feature ?

**Comment by YajanaRao** [comment]
Option to add a track to the favorites
![image](https://user-images.githubusercontent.com/38914337/54662727-f5f5f480-4b04-11e9-8498-6bdcf1ace9cc.png)

**Comment by nukeop** [comment]
Hold on with this for a moment, it's gonna need some big changes in many components and I'm not sure how I want to handle this yet.

**Comment by YajanaRao** [comment]
Okay

**Comment by nukeop** [comment]
Ok, I think I will handle this by introducing a "library" feature, which will group playlists, bookmarked tracks, and bookmarked albums under one menu entry, with its own expandable row in the left hand panel.

**Comment by nukeop** [comment]
![2019-03-26-234308_304x912_scrot](https://user-images.githubusercontent.com/12746779/55038400-00dae880-5021-11e9-96ee-513143675a32.png)

Here's what this is going to look like. Other than tracks, I'll also allow adding artists and albums, but I'm focusing on implementing tracks first. The sidebar menu is redesigned with playlists being displayed directly there, instead of having their own screen, which was not showing a lot of info either way.

**Comment by nukeop** [comment]
Favorite tracks view is complete. I'm just linking appropriate functions to it now.

![2019-03-30-234646_1610x811_scrot](https://user-images.githubusercontent.com/12746779/55282561-6216fa80-5346-11e9-808d-05cf3dbe4a2b.png)

**Comment by nukeop** [comment]
This was fun to implement and it also helped to improve the quality of playlists and sidebar menu, thanks for the suggestion.
