### ISSUE TITLE
Subsonic support

### ISSUE THREAD

**Issue by wioxjk** [nukeop/nuclear#300]
It would be really neat if Nuclear would implement support for Subsonic - this would mean that it would be possible to stream music from alot of different sources, like [Funkwhale](https://funkwhale.audio/), [Ampache](http://ampache.org/) and more.

https://github.com/nukeop/nuclear/issues/11

**Comment by nukeop** [comment]
I'm not very familiar with Subsonic but I can surely try to implement support for it. If any contributors are more familiar with it than me, they're more than welcome to try too.

**Comment by nukeop** [comment]
I took a look at Funkwhale in particular and it's something I'd definitely want to support soon. Once we release 0.5.0 I think this will be the next feature I'll start working on.

**Comment by EliotBerriot** [comment]
Hi there!

I'm Funkwhale maintainer, thank you for considering supporting the Subsonic API in Nuclear! Here is a couple of links you may already have but that can help you with the implementation:

- [Subsonic API documentation](www.subsonic.org/pages/api.jsp)
- [Funkwhale Subsonic API documentation](https://docs.funkwhale.audio/developers/subsonic.html): especially the list of endpoints we support
- [Our demo server](http://demo.funkwhale.audio/): you can use it for your tests, username and subsonic password are "demo" (server is reset every few hours)

It's worth noting Funkwhale doesn't support all the Subsonic API endpoints. In particular, we don't support endpoints that are based on music folders (because at its core, Funkwhale isn't based on music folders), so endpoints like `getMusicFolders` are not working (or returning a dummy response). We support ID3 based endpoints instead. I'm not sure about other popular Subsonic servers, like [Airsonic](https://github.com/airsonic/airsonic).

Typically, Subsonic clients like DSub that support both require you to check a box in the server settings ("Browse with ID3 tags"), to use either directory or id3-based endpoints.

I you find anything wrong or missing with our Subsonic implementation or have any question, just ping me here :) (I'm going to watch the thread anyway)

**Comment by nukeop** [comment]
I think I'm going to use Funkwhale as a reference in the implementation, and if there are any incompatibilities I'll deal with them as they arise. I'm not sure yet what level of integration will be the best - just for streaming media, or using the music discovery features too, etc. I'll try using Funkwhale and maybe start my own server to get a better feel for how it works and how it'll come into the picture when considering interoperability with Nuclear.

**Comment by EliotBerriot** [comment]
> I'm not sure yet what level of integration will be the best - just for streaming media, or using the music discovery features too, etc.

For quick streaming prototyping, you can probably go with the [`stream`](http://www.subsonic.org/pages/api.jsp#stream) (to retrieve a an audio file to stream) and [`search3`](http://www.subsonic.org/pages/api.jsp#search3) endpoints. This should be enough to retrieve a song metadata and play it. The song id from the `search3` call will we the ID to use for streaming.

**Comment by EliotBerriot** [comment]
> I'm not sure yet what level of integration will be the best - just for streaming media, or using the music discovery features too, etc.

For quick streaming prototyping, you can probably go with the [`stream`](http://www.subsonic.org/pages/api.jsp#stream) (to retrieve a an audio file to stream) and [`search3`](http://www.subsonic.org/pages/api.jsp#search3) endpoints. This should be enough to retrieve a song metadata and play it. The song id from the `search3` call will we the ID to use for streaming.

**Comment by nukeop** [comment]
Is there a sort of a "default" server you'd like to direct newcomers to, or should this remain an advanced option only for people who want to use their own server and know what they're doing?

My design philosophy is that users don't necessarily care about the particulars of what service is streaming what to whom, and just want to listen to music, so I try to create sane defaults for people who don't care, while leaving an option to configure stuff for people who do. But maybe this should be explicitly only for people who *do* care about where they're music is coming from.

**Comment by EliotBerriot** [comment]
@nukeop I understand the need for sane defaults, unfortunately, think it will be hard to provide such a default server, at least for Funkwhale, due to the decentralized nature of the service. 

Technically, we could set up a dummy account on https://open.audio (a public Funkwhale instance with public domain music) for that purpose, but this would recreate centralization and a single point of failure, which we try to avoid as much as possible.

> But maybe this should be explicitly only for people who do care about where they're music is coming from.

I tend to agree with this :)

**Comment by nukeop** [comment]
I think I will leave a link to the main page of Funkwhale with a note saying that you'll find the instructions on setting up your own server there. Strictly speaking the functionality will not be limited to Funkwhale anyway, but I feel like this is a good example.

So I think I will add Subsonic as a search provider (for finding metadata about albums, artists, etc) as well as a streaming provider (for finding stream urls).

I see the authentication method differs depending on the API version you're targeting - which one does Funkwhale support? I must say I'm not terribly impressed with Subsonic's authentication protocols, which include sending passwords in plain text via http in path, and hashing with md5 (even though it's salted) with no other algorithms supported (at least according to the docs). Looking at the requests from the web client, you're also using JWT, is that the preferred way?

**Comment by nukeop** [comment]
After a show of extremely unfriendly behavior from the maintainers of Funkwhale, I decided I will not be going forward with this after all, they enjoy policing language more than coding, and they require total obedience to explicitly evil code of conduct they adopted.

**Comment by ealgase** [comment]
You realize that the Subsonic API has nothing to do with Funkwhale, right?

If you want to create it without keeping in mind the Funkwhale COC, nothing's stopping you.  You're just no longer welcome to contribute to the project directly.

**Comment by nukeop** [comment]
Yeah, let me know what else I can do to help Funkwhale bullies and harassers.

**Comment by wioxjk** [comment]
Who has bullied and harassed you?

**Comment by ealgase** [comment]
[This thread](https://mastodon.eliotberriot.com/@eliotberriot/101980218959502151) can provide some information on this situation, in particular [this](https://mastodon.eliotberriot.com/@eliotberriot/101981422230345376) comment.

**Comment by nukeop** [comment]
Nothing says a welcoming, inclusive community like public lynching on local twitter derivative, in the absence of the victim.

**Comment by nukeop** [comment]
It's not going to be easy but I think I will learn to live with that knowledge, in time.

**Comment by wioxjk** [comment]
> [This thread](https://mastodon.eliotberriot.com/@eliotberriot/101980218959502151) can provide some information on this situation, in particular [this](https://mastodon.eliotberriot.com/@eliotberriot/101981422230345376) comment.

Is there any screenshots of the actually conversation?

**Comment by Houkime** [comment]
Sad when human relationships prevent potentially beneficial software development.

Though the mentioned auth problems in Subsonic are worrying and might need to be addressed before inclusion.

Can't help but notice that Subsonic is one of these strange projects that are opensource but do not really advertise this fact and have paid services.
https://sourceforge.net/projects/subsonic/

I remember seeing a game on Itch which was paid-for on itch itself and yet had an unadvertised github repo where one could fetch one for free.
The obvious downside of this is that there are less developers and things get fixed slower.

Returning to Subsonic, more importantly is that the last release tag here https://sourceforge.net/p/subsonic/code/HEAD/tree/ is 6.0 beta 1 and was in 2016 while the latest version here  https://sourceforge.net/projects/subsonic/files/subsonic/ is 6.1.5 and dated 2018-12-1

Which most probably tells us that in 2016 Subsonic went closed-source and proprietary.
This means that unless Funkwhale deliberately froze the subsonic version to 6.0 it is now including a closed binary blob.

This also probably tells us that auth problems might never be fixed in the future.
Which assumption is partly supported by https://sourceforge.net/p/subsonic/bugs/141/
Note that this security problem was reported in 2015(!)

**Comment by nukeop** [comment]
I don't think there's anything to be gained by sharing screenshots or debating this endlessly, and nobody likes rule lawyering. Not the first project ruined by this toxic code of conduct and certainly not the last. Remember to oppose it wherever you see it, it's the scourge of free software.

**Comment by ealgase** [comment]
I have a feeling that the reason you don't want the screenshots distributed is because of how ridiculous this is.
![Screenshot 2019-04-24 at 5 03 15 PM](https://user-images.githubusercontent.com/11603778/56693790-53a4d000-66b3-11e9-8ef3-90cd662c4880.png)
![Screenshot 2019-04-24 at 5 03 29 PM](https://user-images.githubusercontent.com/11603778/56693791-53a4d000-66b3-11e9-9afd-920901b630e1.png)
![Screenshot 2019-04-24 at 5 03 48 PM](https://user-images.githubusercontent.com/11603778/56693792-53a4d000-66b3-11e9-998b-27d4d4e40924.png)
![Screenshot 2019-04-24 at 5 04 06 PM](https://user-images.githubusercontent.com/11603778/56693794-53a4d000-66b3-11e9-8408-7485320d00b2.png)
![Screenshot 2019-04-24 at 5 04 28 PM](https://user-images.githubusercontent.com/11603778/56693795-53a4d000-66b3-11e9-8b9c-49542bf3140d.png)
![Screenshot 2019-04-24 at 5 04 45 PM](https://user-images.githubusercontent.com/11603778/56693796-543d6680-66b3-11e9-82f0-5d18679a6c22.png)
![Screenshot 2019-04-24 at 5 05 05 PM](https://user-images.githubusercontent.com/11603778/56693798-543d6680-66b3-11e9-9b18-a5b6d5da970f.png)
![Screenshot 2019-04-24 at 5 05 31 PM](https://user-images.githubusercontent.com/11603778/56693799-543d6680-66b3-11e9-86a4-fe8037c4e66e.png)
![Screenshot 2019-04-24 at 5 05 52 PM](https://user-images.githubusercontent.com/11603778/56693800-543d6680-66b3-11e9-8b35-cf813fd42ce2.png)

**Comment by nukeop** [comment]
Of course it's ridiculous, and yet you go out of your way to harass me even further.

**Comment by ealgase** [comment]
I'm not trying to harass you.  All I did was post the screenshots of what was said.  Do you stand by your words? Because it seems like you're censoring me a lot more than Funkwhale ever has.

[the post I made is available here](https://web.archive.org/web/20190424210718/https://github.com/nukeop/nuclear/issues/300)

**Comment by nukeop** [comment]
Yes you are, and yes I do, but i also think this is the stupidest thing in the history of open source software to make a scene over. I don't know who you are, and I have no idea why you're so invested in this, so I think this will be your last post here, for any further questions please visit the support channel.

**Comment by TrollDecker** [comment]
You're not the good guy in this situation, borg boy. Not even by a mile.

**Comment by nukeop** [comment]
Who are you?

**Comment by TrollDecker** [comment]
Someone who thinks you're little more than a spoilt shit who've never been told "no" once in his prissy life.

Grow up, kid.

And learn an actual GUI toolkit.

**Comment by nukeop** [comment]
Thank, you your feedback is very important to us. Please stay on the line.

**Comment by TrollDecker** [comment]
Go back to your child porn.

**Comment by nukeop** [comment]
Bye bye.

**Comment by TrollDecker** [comment]
Go back to your child porn.
