### ISSUE TITLE
shortcomings of the program

### ISSUE THREAD

**Issue by mrkaban** [nukeop/nuclear#373]
The track switch keys and the pause do not work, considering that we all have different tastes, switching the track if you do not like is not possible.

There is no possibility to add immediately a category of music tracks, which makes the program completely uninteresting.

silent installation is blocked by antiviruses, so you have to add to the white list (BitDefender).

did not notice the ability to mix the playlist.

If a personal opinion, then I would say that I did not like the music in the assortment at all.

**Comment by nukeop** [comment]
Hi, thank you for the feedback. We have our best specialists working around the clock to deliver the best quality software possible, and user feedback means a lot to us.

You are correct that there is no way to add all tracks from a tag to a playlist, so I will add this to the backlog to be implemented.
There is a shuffle mode, which plays tracks in a random order. It can be enabled near the volume controls, or in the settings.
We are not responsible for the available music or recommendations, since they are sourced from third party sites.

**Comment by mrkaban** [comment]
Thank you very much for the program!

Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0/%D0%BF%D1%80%D0%BE%D1%87%D0%B5%D0%B5/nuclear-%D0%BF%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%B2%D1%8B%D0%B9-%D0%BC%D1%83%D0%B7%D1%8B%D0%BA%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%BF%D0%BB%D0%B5%D0%B5%D1%80.html).

The project is interesting, so please don't abandon it!

**Comment by nukeop** [comment]
Thanks, I'm still working on it! I promise to keep improving it!
