### ISSUE TITLE
Create classes for Artists, Tracks, Albums, etc

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#458]
This is an issue for me so I can keep track of my progress implementing some basic data structures for the concepts commonly used throughout the program. These will define all the required fields for each category and will be used to normalize data coming from different sources. They should be easily serializable and reusable between the server and web app. I think I will create a separate package for this.

**Comment by emlautarom1** [comment]
Lucky me, I was just about to implement them myself. It looks like every resource handles their own version of `track` and `album` object, making it hard to be consistent and implement proper logic.

Do you have an initial draft/idea on how these classes should look? Specially the `uuid` part. That should solve a lot of problems, like the favorites functionality.

I saw the `safeAddUUID` that you added here:

https://github.com/nukeop/nuclear/blob/8971a5ed5d9b3553efdfb4954eff180b5ae3e0b8/app/actions/queue.js#L19

Currently, it only allows to delete favorite tracks that have been added in the same session, because the `uuid` was generated in that particular session. Adding a track to favorites, then restarting the app, makes the track imposible to remove, since a new `uuid` has been generated for that track.

I thought of using the `mbid`, wich comes from an external source (musicbrainz), but some tracks don't have that id.

**Comment by karevn** [comment]
I think class-based approach does not work well in JS. As classes tease people to use an inheritance, then the inheritance chain grows and SRP gets violated. I really recommend to look towards a layered service-oriented architecture, probably involving something like a gorgeos redux-query lib or React hooks + some service layers.

Ideally, it would look the next way:
1. network layer - something like a fetch or superagent wrapper.
2. "routing" layer, responsible for generating URLs, telling GET / POST requests from each other and managing custom headers.
3. "Interface adaptor" layer, responsible for converting web service data structures to the ones used by Nuclear internally.
4. Redux state adapter, responsible for correctly updating it upon requests.
5. "Loading spinner" manager not to reinvent the loader logic over and over again.

All these layers can be written without classes by composing functions and React components, and I can put together a reference implementation for, say, "top tracks" or something like that the next week.

**Comment by nukeop** [comment]
I don't think we'll use inheritance at all. I'm not warped by Java so I don't feel inclined to create crazy inheritance chains. I only want to create some common ground for conversions between different formats of data from different sources (such as last.fm, discogs, musicbrainz, etc, which right now are loaded into Redux and converted as needed in components that use them). I'm also thinking of using a local database for storage, perhaps SQLite or Postgres, and this will naturally translate into db tables.

**Comment by karevn** [comment]
Please take a look at this PR: https://github.com/nukeop/nuclear/pull/462
Using such an approach, we can create a bunch of "api adapters" based on pretty simple functions, and get some nice features like per-component loaders, retries and much better code cohesion for free.
