### ISSUE TITLE
Video Image overlapping setting button

### ISSUE THREAD

**Issue by as3mbus** [nukeop/nuclear#47]
this is awesome project. i would like to contribute by submitting some or many issue.
this is one of it :x 
i need to toggle full screen mode to be able to access it.

![image](https://user-images.githubusercontent.com/16043293/30920424-188f474c-a3ce-11e7-9ce4-6c9f4c57daf6.png)

i'd like to help with the code but i dont have any skill in electron so. i guess will need to learn about it

**Comment by as3mbus** [comment]
oh yeah there are many other issue that i want to submit but should i open many issue or just pile it up in 1 issue :x

**Comment by nukeop** [comment]
Thanks for letting me know. The layout is buggy in this version, that's why I decided to start from scratch for 0.4.0. It will look much better even on tiny screens in the new version. Here's a preview of the new layout:

![image](http://i.imgur.com/vlR4ekw.png)

These changes are available on the rewrite branch, as well as in a separate repo (check the repositories list on my github page).

**Comment by as3mbus** [comment]
awesome. gonna check it later when i got better connection
