### ISSUE TITLE
Add all tracks to the queue.

### ISSUE THREAD

**Issue by March0514s** [nukeop/nuclear#563]
When you find and select a particular artist, nuclear displays along with similar artists, a smaller version of the list with the popular tracks and an "+ Add all" button, that only adds the displayed tracks to the queue, and I suggest that this button behavior be changed to really add all the artist popular tracks available (that become displayed after you click the double arrow button at the bottom of the track list) instead.

![image](https://user-images.githubusercontent.com/4138199/70354525-84a2d100-184e-11ea-935a-cd2c0816d7ab.png)

**Comment by nukeop** [comment]
Ok, fair suggestion, I'll change it.

**Comment by WildLeons** [comment]
Hello,
I've been testing stuff to fix this bug and it seems to be working.
Can you check it out for me?

In this file : https://github.com/nukeop/nuclear/blob/master/packages/app/app/components/ArtistView/PopularTracks/index.js
I replaced line 94: ".slice(0, expanded ? 15 : 5)"
by ".slice(0, tracks.length > 15 ? 15 : tracks.length)"

The old line required to first scroll down the list before adding the singles to get all of them otherwise we only have the first 5.
Now it is not necessary to do this anymore and I checked for artists who have less than 15 singles on the platform with the artist "GRIGRI" for example.

**Comment by nukeop** [comment]
Fixe by @WildLeons
