### ISSUE TITLE
Scrolling issue with new simple list in local library

### ISSUE THREAD

**Issue by Mongogamer** [nukeop/nuclear#568]
- **Nuclear version**: 0.5.0 commit 331521a7ba41c898ced62e97365b60295a05cf6e
- **OS**: Windows 10 Pro x64 1909
- **NodeJS version**: 12.12.0
---
**Description of the issue**: Since the new album layout has been added to the local library there have been some scrolling issues with the simple list. The scrollbar constantly jitters around and completely resets if dragged too low.
Here is a short video showcasing the issue:
[https://streamable.com/357vq](https://streamable.com/357vq)

**Comment by nukeop** [comment]
Yes, this is an unfortunate consequence of using react-list for virtualization. It populates the list as you scroll down. I thought that it would be more natural to filter first, but looks like it was a wrong assumption. The problem we tried to address was that with a large library rendering all of the tracks would quickly become very slow and inefficient.

**Comment by Venryx** [comment]
> Yes, this is an unfortunate consequence of using react-list for virtualization. It populates the list as you scroll down.

It's confusing to me that he's having so much jittering, because I didn't notice substantial jittering when I first integrated react-list. (video here: https://github.com/nukeop/nuclear/pull/546)

Is there something that was changed about the simple-list view since then?

If not, then I'm guessing it must have to do with the "itemSizeEstimator" option sent to react-list. It's used to determine how much "space each item takes up", before react-list is actually scrolled to the area where it's to be shown. Once it scrolls there and the item renders, the estimated-size is replaced with the "actual size", causing the scroll-height of the container to be updated.

A large difference between the estimated-size and the actual size must be what is causing the jittering (if it's not from some higher-level code change).

@Mongogamer Can you check the actual item heights in your track list, by using the dev-tools? (The value sent as itemSizeEstimator is 44px)

> I thought that it would be more natural to filter first, but looks like it was a wrong assumption.

Is there a block of code you can point to to describe this? Might help diagnose what's going wrong.

**Comment by nukeop** [comment]
It's more to do with predicted user behavior patterns than code.
itemSizeEstimator is still at 44, and while I changed some stuff around library view, I didn't change how the tracks are rendered.

**Comment by Mongogamer** [comment]
It used to work well even when #546 was  merged. This issue only popped up for me once the Album Grid got merged into master.

**Comment by nukeop** [comment]
Ok, I'll look into it, must have messed up something. Your bug reports are the best.

**Comment by nukeop** [comment]
I made the items uniform in height and changed the list type to uniform, and to me it looks smoother than what you've shown in your post (I was able to reproduce it on my machine too). I also added keys to ContextPopups that renders the track rows. Without keys, react will re-render the entire list every time it changes, causing a noticeable lag, and it seems that it's not enough to have them on the track rows, even though they end up being rendered to DOM, because the popups are directly in the list in React's virtual DOM.

**Comment by Mongogamer** [comment]
I can't seem to load any songs into the library since 0ba30d209cd4a134a6b898be7a40085b2311acbd so testing the changes currently isn't possible for me.

**Comment by nukeop** [comment]
You were 100% correct, I introduced a bug. I fixed that now.

**Comment by nukeop** [comment]
You can try it now, library should be both faster and scroll smoother (there's still a display bug when there's less than ~5 tracks but I'll work it out before the next release).

**Comment by Mongogamer** [comment]
Something seems to go wrong when trying to run/build on Windows. Lerna outputs this and then gets stuck:
```main › something fail during app bootstrap
    main › Error: Missing required @injectable annotation in: WindowsMediaService.
    at getTargets (webpack:///./node_modules/inversify/lib/planning/reflection_utils.js?:21:15)
    at Object.getDependencies (webpack:///./node_modules/inversify/lib/planning/reflection_utils.js?:12:19)
    at eval (webpack:///./node_modules/inversify/lib/planning/planner.js?:106:51)
    at Array.forEach (<anonymous>)
    at _createSubRequests (webpack:///./node_modules/inversify/lib/planning/planner.js?:94:20)
    at eval (webpack:///./node_modules/inversify/lib/planning/planner.js?:115:17)
    at Array.forEach (<anonymous>)
    at eval (webpack:///./node_modules/inversify/lib/planning/planner.js?:114:26)
    at Array.forEach (<anonymous>)
    at _createSubRequests (webpack:///./node_modules/inversify/lib/planning/planner.js?:94:20)```

**Comment by nukeop** [comment]
Travis builds it now on all platforms, but there are some bugs introduced by the refactor, we'll need a few days to make things stable again.

**Comment by nukeop** [comment]
Although loading the library looks ok right now

**Comment by Mongogamer** [comment]
I can confirm that the build does indeed succeed, the created Windows executable is unable to launch however. Lerna somehow manages to pass all tests, report success at building all 3 packages and still produces an unusable binary.
Building on Linux in a VM worked perfectly fine for some reason but even there the Windows build wouldn't work at all.

Currently Lerna outputs this error when trying to run the development version on Windows:
```bash
info cli using local version of lerna
lerna notice cli v3.19.0
lerna info Executing command in 3 packages: "npm run start"
lerna info run Ran npm script 'start' in '@nuclear/common' in 2.4s:

> @nuclear/common@0.5.1 start C:\Users\xxxxxx\Desktop\nuclear\packages\common
> tsc ./src/index.ts --declaration --outDir lib

lerna info run Ran npm script 'start' in '@nuclear/main' in 9.3s:

> @nuclear/main@0.5.1 start C:\Users\xxxxxx\Desktop\nuclear\packages\main
> rm -rf build && webpack --env.NODE_ENV=development && electron build/main.js


    main › development Env variables loaded
    main › Initialized settings store at C:\Users\xxxxxx\AppData\Roaming\Electron\config.json
    main › Initialized library index at C:\Users\xxxxxx\AppData\Roaming\Electron\nuclear-local-library.json
    main › something fail during app bootstrap
    main › Error: The controller WindowsMediaService has no event registered, you must register at least one
    at eval (webpack:///./src/utils/decorators.ts?:29:19)
    at DecorateConstructor (webpack:///./node_modules/reflect-metadata/Reflect.js?:541:33)
    at Object.decorate (webpack:///./node_modules/reflect-metadata/Reflect.js?:130:24)
    at __decorate (webpack:///./src/services/system-api/win.ts?:5:92)
    at eval (webpack:///./src/services/system-api/win.ts?:17:23)
    at Module../src/services/system-api/win.ts (C:\Users\xxxxxx\Desktop\nuclear\packages\main\build\3.main.js:12:1)
    at __webpack_require__ (C:\Users\xxxxxx\Desktop\nuclear\packages\main\build\main.js:26:30)
    at eval (webpack:///./src/services/system-api_lazy_^\.\/.*$_namespace_object?:49:10)
```

**Comment by nukeop** [comment]
@charjac is still making some changes in https://github.com/nukeop/nuclear/pull/576

After that and maybe some additional bugfixing, everything should work.

**Comment by charjac** [comment]
oops sorry for that i make a fix in my PR

**Comment by Mongogamer** [comment]
After the #576 merge I can build on Windows again. Scrolling feels much smoother now but dragging the scrollbar to the bottom is still impossible. It seems to be caused by the scrollbar becoming smaller as more tracks are added, making it unable to reach the bottom and entering a continuous scrolling mode.

**Comment by Venryx** [comment]
Found the fix for the issue @Mongogamer hit above; just add this to the `<ReactList...>` element in `LibrarySimpleList/index.js`:
```
<ReactList
    ref={comp => {
      // needed to fix "height" style being ignored (thus breaking scrolling)
      comp.el.style.display = 'table';
    }}
    ...
/>
```

React-list was correctly setting the `height` value for the table, but for some reason it was being ignored by the browser renderer with the default `display: block` style. Switching the display-type to `table` fixes this.

**Comment by Mongogamer** [comment]
With @Venryx fix the local library scrolls incredibly smoothly and quickly even with a very large amount of tracks. Feel free to tag this issue for automatic closing in your pull-request.
