### ISSUE TITLE
White screen appears when artist is selected

### ISSUE THREAD

**Issue by ItsMeAtd** [nukeop/nuclear#60]
Sometimes the app freezes with a white screen when you click on an artist or try to play a song , I can play the artist songs when browsing through albums but not the artist page .

**Comment by nukeop** [comment]
Can you tell me which artist causes this?
I noticed there are some gaps in the data I'm getting from Discogs, might have to switch to a different provider.

**Comment by ItsMeAtd** [comment]
The bug appears mainly when I try to play K-pop artists ( GOT7 / Twice / Red Velvet / EXID) I did manage to play their songs if I searched for the albums though

**Comment by nukeop** [comment]
I'll look into it. Some links are incorrect and point to nonexistent pages.

**Comment by NightMachinary** [comment]
I get the white screen at startup! :(

**Comment by nukeop** [comment]
Which version and what system?

**Comment by NightMachinary** [comment]
This:
https://github.com/nukeop/nuclear/releases/download/v0.4.2/nuclear-0.4.2.dmg

**Comment by nukeop** [comment]
I'll try to build newer binaries today (0.4.3), and let you know when they're ready.

**Comment by NightMachinary** [comment]
Thanks👍🏻

**Comment by pqrth** [comment]
@nukeop I tried [nuclear-0.4.2.dmg](https://github.com/nukeop/nuclear/releases/download/v0.4.2/nuclear-0.4.2.dmg) and [nuclear-0.4.0.dmg](https://github.com/nukeop/nuclear/releases/download/v0.4.0/nuclear-0.4.0.dmg) on macOS 10.13.5, but the app window is completely white as @NightMachinary shared:

![image](https://user-images.githubusercontent.com/6792160/41824155-57eccc90-7829-11e8-8687-02736367b68d.png)

**Comment by nukeop** [comment]
Hm, the problem seems to be that youtube and other services change their APIs often, and when that happens, previous versions get broken. I'll try to figure out if that's what happened here and update relevant packages and release 0.4.3 soon...

Also there's a problem with broken data on Discogs (e.g. links to non-existing albums), which might force me eventually to use Musicbrainz.

On another note, clearly a log file is needed so we can figure out what's going on when you get a blank screen. And probably better response to errors.

**Comment by pqrth** [comment]
Thanks a ton for the fix @nukeop. I built the master branch at commit 2ccc96e for macOS 10.13.6, and I can confirm that this issue is fixed.

Now, my `npm install` had failed due to `No package 'dbus-1' found`. So instead of removing optional dependency as suggested in the [_README.md_](https://github.com/nukeop/nuclear#dev-build-process), I installed the package [_d-bus_](https://formulae.brew.sh/formula/dbus) via [Homebrew](https://brew.sh) (`brew install d-bus`) and then the missing package was found.

@nukeop Do you think these instructions would be helpful in the README? If so, I can create a pull request to add them.

**Comment by nukeop** [comment]
dbus is a Linux subsystem and as such is specified as an optional dependency. While it probably can be installed on Macs, I doubt that it'll do anything useful. On Linux, it's used for communicating with system widgets that can control the player.

Since you're saying that installation fails, this must mean that specifying it as an optional dependency is not enough (there should be a warning, but it should succeed nonetheless). In fact, there are two sets of different electron server files specifically for this reason (considering that dbus will not be present by default on MacOS and Windows).

If you want, you can add the instructions as a temporary workaround until we can figure out how to skip it completely.
