### ISSUE TITLE
Request: Search option for unreleased music

### ISSUE THREAD

**Issue by happydemic** [nukeop/nuclear#62]
Long-standing user here (since cole I think!)

My main use case for Nuclear was to listen to unreleased music not available on traditional platforms, such as unsigned artists, live versions of new material, live covers etc. This functionality seems to have disappeared with the new search method in 0.4.0 and higher, so I've gone back to 0.3.0.

I wonder if you might consider introducing an "Advanced" search mode which includes the old search functionality, making it possible once again to search directly in the music sources for unreleased music that isn't eligible for inclusion in Musicbrainz? The new search via Musicbrainz looks great and works really well, but unreleased tracks are not added to the Musicbrainz database, so searching for them comes up empty. It's also no longer possible to select an unreleased live version of a released track, even if it's on the artist's official channel. 

Apologies if this feature is still there and I've managed to miss it.

**Comment by nukeop** [comment]
You're right, the feature isn't there anymore, mainly because I considered it too inconvenient to use.

There's an option in the dev version now to change the stream found automatically to find live and other alternate versions. I might make it more advanced in the future, what do you think?

Would you like to have an option to browse through all tracks returned from youtube for a given search term? Or would you like to be able to search for anything in any supported plugin (youtube, soundcloud, etc) and add it to the queue?

I'm using Discogs as the metadata search provider right now, not Musicbrainz. In the future I'll either switch to Musicbrainz or combine them somehow because Discogs alone tends to be inaccurate and filled with garbage data.

**Comment by HaiDang666** [comment]
implemented
