### ISSUE TITLE
invidious api

### ISSUE THREAD

**Issue by charjac** [nukeop/nuclear#627]
What about using invidious api =>  https://github.com/omarroth/invidious
and use youtube plugin as a fallback when something fail.

https://github.com/FreeTubeApp/FreeTube use it and it works just fine.

This could be configurable in the settings:
 - invidous instance url
 - enable/disable

**Comment by nukeop** [comment]
This could be developed as a stream provider plugin, and then swapped in as the default one if it looks good.

What does it give us though? If it's just a frontend to Youtube (which in a way Nuclear is too)?

**Comment by charjac** [comment]
if i understand correctly, it exposes an api => "Does not use any of the official YouTube APIs".
I will investigate on this side, it could be interesting to offer the possibility to not use google stuff.

**Comment by nukeop** [comment]
Oh, that sounds very good indeed. We've had some issues with users being rate limited or blocked due to running out of api key capacity. And basically right now we have to hope that we're still under Google's radar because they could fairly easily block us altogether if they wanted. That would decouple us from them permanently.

**Comment by charjac** [comment]
Ok, i start working on it.

**Comment by charjac** [comment]
here is an api documentation https://github.com/omarroth/invidious/wiki/API

**Comment by limengyu1990** [comment]
https://github.com/LIU9293/musicAPI
