### ISSUE TITLE
Replace version in the lefthand sidebar with git hash

### ISSUE THREAD

**Issue by nukeop** [nukeop/nuclear#633]
I'd like to start releasing on every push to master and automate whatever is possible, so explicit versioning will make less sense. I think this can be done by utilising the webpack define plugin.

**Comment by NettoHikari** [comment]
To he honest, the average joe is not interested in seeing the version number or version hash all the time. Should be tucked away in an about dialog.

**Comment by nukeop** [comment]
Maybe, but it doesn't take that much space and we have plenty of room in the sidebar anyway. It's useful when people report bugs and want to find out what they're actually running.

**Comment by NettoHikari** [comment]
I get where you're coming from. But IMHO the interface is quite sleek and "minimalist", but having the logo and git hush in there kind of ruins it. Maybe add an option to hide it?

I would love that.

**Comment by nukeop** [comment]
Yes, this is a good idea.

**Comment by Korb** [comment]
> To he honest, the average joe is not interested in seeing the version number or version hash all the time. Should be tucked away in an about dialog.

You're right. In order to check for a new version, I checked both places where I usually see it. And in none of them I saw neither the current version number, nor the "Check for new version" button, nor the notification that a more recent version than the current one is available for download:

![Screenshot_2022-11-14_08-53-54](https://user-images.githubusercontent.com/3509797/201586710-a7d21f4b-694d-4866-976b-52d22e23d77e.png)

![Screenshot_2022-11-14_08-53-10](https://user-images.githubusercontent.com/3509797/201586706-577df061-1667-4d54-8942-8bbf6efd58a0.png)

**Comment by nukeop** [comment]
I'll be replacing the current versioning scheme with a return to regular semantic versioning, so the version number will return to its usual place.

**Comment by nukeop** [comment]
It's using semantic versioning now. The current version is shown on hovering over the logo
