### ISSUE TITLE
Wrong similar artist page

### ISSUE THREAD

**Issue by mr00z** [nukeop/nuclear#667]
When you try to go to the page of one of the similar artists, in some cases app redirects you to either some other random artist or a 'blank' artist page. Some examples:
1. Go to _Lorde_ artist page
2. Select _Lana Del Rey_ from similar artists list
3. App displays _Zachary Richard_ artist page instead

or

1. Go to _System of a Down_ artist page
2. Select _Korn_ from similar artists list
3. App displays 'blank' artist page instead

I am not able to identify any clear pattern when this happens. However, I noticed that when selecting Lana Del Rey from similar artists list (e.g. from the one of Billie Eilish) app always redirects you to Zachary Richard's page. This pattern also works for other artists e.g. selecting Marina from similar artists list always gives you Peter Lazonby's page.

Nuclear version: 0.6.3
OS: Windows 10 (x64)

**Comment by nukeop** [comment]
I've also noticed this. It's a problem caused by Discogs; their catalog is sometimes messy or incomplete, and contains incorrect links, which redirect you to wrong albums.

Similar artists are downloaded from last.fm, and then searched for using names. If the artist has a last.fm entry, but isn't on Discogs, you'll end up on the wrong page. This can also be caused by a bug in the search-by-name function, since the artists you noticed this for are pretty popular and likely to be in the catalog.

I'm currently rewriting the way search works so maybe this problem will go away soon. I will revisit this after I merge my changes.
