### ISSUE TITLE
Add Homebrew Cask support

### ISSUE THREAD

**Issue by NightMachinary** [nukeop/nuclear#67]

**Comment by adamlaz** [comment]
I'm considering opening a PR to impliment this...  Will be a good way for me to learn how to make a cask! [documentation here](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md). 

Do you guys think Nuclear is too similar to the notorious Popcorn Time? There are [cask approval guidelines](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md)... and one of their [rejected examples is actually for popcorn time](https://github.com/Homebrew/homebrew-cask/pull/3954).  Personally, I don't think so ... but may not be approved because of the description in this repo..."Popcorn Time for music". 

If I have time this weekend I'll open a PR and we can see!

**Comment by nukeop** [comment]
I think it was because of too many forks and malware versions and at some point nobody even knew which version was going to be the official continuation of the original program. Although I agree that it's a bad system if a piece of software can be "rejected" from a package manager by a bunch of people on a whim. Who knows what they're not going to like with this piece of software? Thanks for your contribution.

**Comment by trekiteasy** [comment]
Regarding this "popcorn time for..." question, I noticed it was mentioned quite a bit in a couple of issues & discussions about nuclear. I would suggest changing this to something more realistic (ie. not including torrents / popcorn time) and more acceptable (ie. a decentralized / multi-source music streaming player)... I don't have a good wording coming out for this right now. But I think we should think about it.

**Comment by nukeop** [comment]
I made this thread: https://github.com/nukeop/nuclear/issues/140

**Comment by vitorgalvao** [comment]
[Just added to Homebrew Cask](https://github.com/Homebrew/homebrew-cask/pull/70712) by @kvsm.

This can be closed.

> Do you guys think Nuclear is too similar to the notorious Popcorn Time?

I have no knowledge of how different Nuclear was at the time of that comment, but as it is now, I don’t see a problem with it. Popcorn Time was a special case that we decided against [considering all that happened with the project](https://github.com/Homebrew/homebrew-cask/pull/3954).

**Comment by nukeop** [comment]
Cool, very nice of him to help.
