### ISSUE TITLE
Lerna start does not launch UI package's start in "watch" mode

### ISSUE THREAD

**Issue by Venryx** [nukeop/nuclear#691]
Lerna start launches `cd packages/ui; npm run start`, however, this task is defined as:
```
tsc && copyfiles -u 1 ./lib/**/*.scss ./dist
```

Notice that the `tsc` portion does not contain the `-watch` flag, so changes to code under the ui directory does not get shown when you refresh the electron window.

It seems inconsistent to have some packages in watch mode and with hot-reload (eg. `packages/app`), and others not even watch mode.

Is this intended behavior, or should it be changed to use the `-watch` flag?

**Comment by nukeop** [comment]
Should definitely be changed. Typically when I develop components in the ui package I use storybook to test them, and when I'm done with that part, I start integrating them into the app with no further changes in the ui package, that's why it didn't bother me. I can see however how it can be annoying for people with different development flows.

**Comment by nukeop** [comment]
This needs more than just the -watch flag. Scss files also need to be copied or be available for import. We could skip the tsc part if the app package had support for typescript, which should come soon.

**Comment by nukeop** [comment]
works now
