### ISSUE TITLE
Docker-Compose rework

### ISSUE THREAD

**Issue by primeapple** [nukeop/nuclear#699]
Hi again.

I would like to talk about the docker-compose config a bit. The reason is, that we then could move directly to docker and won't even need npm installed on the local machine anymore!

There are several things that seem a bit confusing to me.

1. In the docker-compose.yml you have to services. However, the `install` service seems to be not used? Can it be removed?
2. Why do you have to run `lerna exec npm rebuild node-sass`? Why is sass needing to be rebuild?
3. Why do you run `lerna run start`? Wouldn't it be better to run `lerna run build` and then execute the built app?

Overall I would like to restructure the docker setup like this: https://dev.to/alex_barashkov/using-docker-for-nodejs-in-development-and-production-3cgp

What are your thoughts about this?

EDIT: Also I am curious about the [this Dockerfile](https://github.com/nukeop/nuclear/blob/master/Dockerfile). Is it still used anymore? What is with the docker scripts in the [package.json](https://github.com/nukeop/nuclear/blob/master/package.json)? Are they used anymore?

**Comment by nukeop** [comment]
`install` is used in the `dev` service (depends_on list).
`node-sass` uses native modules that need to be rebuilt in case of different node versions, if they're compatible it won't rebuild them.
`lerna run start` starts the program in dev mode, which is the purpose of this config. `lerna run build` would build the program in production mode.

That article you've linked is about pure node apps, most of it won't apply to this use case, for a number of reasons (e.g. Nuclear has a different build process than what's described there, because it has multiple packages that need to be built, in both dev and prod environments, so they all need dev dependencies, we also don't want to copy the code inside the container).

The dockerfile and package.json script at the bottom of your post exists because somebody wanted a way to build and run the program inside a container, which they contributed.

**Comment by primeapple** [comment]
Thank you so much for your answers!

Since `install` uses the same Docker file as `dev` it does exactly the same as dev. So the `install` container is build and also up, but is not used at all from my understanding.

The thing with the current docker container is, that we actually DO copy everything in the repo into the docker-container (see last line in `Dockerfile_dev`). That is not how to use docker, you would want to exclude any unused stuff (node_modules mainly) and built everything from scratch in Docker. This way it makes sure that the project works the same way on any computer, no matter which node_modules were installed before.

In the end this should work on any pc without trouble:
```sh
# clone new instance of nuclear somewhere
git clone https://github.com/nukeop/nuclear.git
# start docker-compose, rebuild it if you
# we don't need dev here since everything is started anyways
docker-compose up --build --force-recreate
```

You will see, that this will not work at all.

If you dont believe me, look at this link: https://nodejs.org/fr/docs/guides/nodejs-docker-webapp/ or this one about lerna and docker: https://versatile.nl/blog/deploying-lerna-web-apps-with-docker

Would it be fine for you, if I try to rewrite the docker-compose? It would make the project much easier to be picked up by new developers.

**Comment by nukeop** [comment]
Do you want node_modules to be installed inside the container? We mount the root as a volume inside the container under `/nuclear`, which lets us use local node_modules and code already. The only thing that needs to be reworked is the `install` service so that it can install dependencies from scratch. Maybe we could skip the `ADD . /nuclear` step as well.

The production Dockerfile could be trimmed by turning it into a multistep build where we only used the relevant binaries and archives in the last step, with build dependencies completely omitted.

To comprehensively test this approach, we could also create github actions that attempt to run these containers.

**Comment by primeapple** [comment]
> Do you want node_modules to be installed inside the container?

This is exactly what I want. 

> The production Dockerfile could be trimmed by turning it into a multistep build where we only used the relevant binaries and archives in the last step, with build dependencies completely omitted.

I will look into this, but it seems like the smaller problem. First I want to get the development container working and make it just as usable as if you would have installed NPM locally.

**Comment by primeapple** [comment]
So I found this article, that describes the best on how to use docker for development: https://hackernoon.com/a-better-way-to-develop-node-js-with-docker-cd29d3a0093

This seems to be the best way. I will try to get it running with lerna.

**Comment by primeapple** [comment]
Is there any interest from your side about this issue? Otherwise I would close it, as sad as it would be. It's your project after all.

**Comment by advaithm** [comment]
I don't see this being useful for most devs as most people feel docker/docker-compose is complicated, This would be useful for some people but for most of us. If you feel people might use it you can work on it. Most of the devs on this project don't use docker.
