### ISSUE TITLE
Not able to set-up nuclear locally

### ISSUE THREAD

**Issue by thisisprasad** [nukeop/nuclear#789]
I'm trying to set up nuclear on my machine by following the development process given in **README.md**. Whenever I run "npm install", a long error gets printed on cmd.
The installation procedure installs dependecies successfully till ``` lerna success Bootstrapped 5 packages ```. After this errors are getting reproduced due sqlite and _.cc_ files.

I have attached the error logs that are being on cmd.
I'm on windows 

Can someone please help me.
Thanks in advance!!
[nuclear_install_logs.txt](https://github.com/nukeop/nuclear/files/5468635/nuclear_install_logs.txt)

**Comment by armte** [comment]
I'm also having a hard time starting up nuclear locally. A little background, I've finished classes for a computer science degree and had access to linux machines for development of lower-level code....so i'm comfortable with a Linux based command line and got WSL for my windows machine to maintain that comfortability. I'm running all these commands in WSL and I think the issue that I'm having is that it appears to install correctly but I get errors when I try to execute the `npm start` command:
![image](https://user-images.githubusercontent.com/35428643/97788264-1d8cba00-1b8e-11eb-99e5-9031106dc0e4.png)
![image](https://user-images.githubusercontent.com/35428643/97788277-372e0180-1b8e-11eb-8ba8-aabfa2762130.png)

I wonder if one of the issues is with running everything in WSL. Lerna recognizes the platform as Linux and I wonder if that's correct or not given the context that it's a windows machine but with a linux subshell running the commands....? Any help would be appreciated! I'm thinking of giving up and just running everything in windows command line/powershell.

**Comment by armte** [comment]
So i was actually able to get Nuclear to finally run. I had to do everything through powershell and it did seem that at least one of the issues with the wsl (linux subsystem) was that the when the native dependencies were being built, the platform was identified as linux instead of windows.

However, no music will play and i receive this error whenever I attempt to play a song:
![image](https://user-images.githubusercontent.com/35428643/97792074-cac3fa00-1baf-11eb-8209-82292fe4a2dc.png)

Any insights into what's going on?

**Comment by thisisprasad** [comment]
The project uses 4.2.0 version of sqlite3. I have downgraded my node from v14.x to v12.x
But still no progress. Not able to build or "npm install" successfully.

@armte Thank you for sharing your findings and results.
