### ISSUE TITLE
Create Snap Package

### ISSUE THREAD

**Issue by feliciakrismanta** [nukeop/nuclear#84]
It's possible that on Ubuntu 18.04 LTS Snap comes preinstalled, it might be a good idea to prepare the package.

https://docs.snapcraft.io/build-snaps/electron

**Comment by benyanke** [comment]
Another note too - if you do set up a snap package, I'd highly encourage you to take advantage of the various "channels" available, so that people can easily track the master branch for simple testing and bug reporting. Telling people "run 'snap install nuclear --edge' and see if that fixes your bug" is far easier than "grab and build and see if you can reproduce it"

**Comment by owais** [comment]
Snap package published to the snap store would be great.

**Comment by nukeop** [comment]
Nuclear is available on snap store now, the only thing remaining is to automate deployment, but it;'s a separate issue.
