### ISSUE TITLE
Use Spotify Api to get metadata videos

### ISSUE THREAD

**Issue by rasyidrafi** [nukeop/nuclear#945]
Spotify has a good recommendation content based on currently song, wondering if this can be implemented

**Comment by HaiDang666** [comment]
Spotify requires API key. Recently I don't see any work around solution. About auto-radio, I gonna implement YouTube related video.

**Comment by nukeop** [comment]
Yeah, we can't use Spotify since that would get us banned instantly. We're thinking about letting users use Spotify-related features if they supply their own api key.

As for the related youtube videos, I think it would be nice if we had a way of selecting the videos to add, but first we need to extract metadata from the titles in a smart way (possible to do with regexing the video title and cross-referencing the artist name/track title with discogs or musicbrainz).

**Comment by HaiDang666** [comment]
I found a potential package for integrate with `spotify` https://github.com/SwapnilSoni1999/spotify-dl 
Need more investigation

**Comment by UltraBlackLinux** [comment]
Why is this closed? I haven't seen a way to enter an api key for Spotify. Some artists I really like only seem to use spotify, so this is kind of a bummer.

**Comment by nukeop** [comment]
I don't think a significant enough number of users would even use it. If anyone wants to contribute this functionality, sure, but I already have a lot planned out without it, and it would take a really significant effort to write tests and implement all of this.
