### ISSUE TITLE
Optimize play queue

### ISSUE THREAD

**Issue by HaiDang666** [nukeop/nuclear#984]
According to discord:

> Just a really stupid question, when i click on "Add playlist to queue" is it supposed to queue up the ENTIRE playlist?
A playlist with like 300 tracks will take forever and use ram like crazy xD
Is there any way to just queue them one at a time, automated, of course?

[message link](https://discord.com/channels/647373417091170314/647373417091170317/851512763234779206)

**Comment by nukeop** [comment]
An item in the queue is just a string of text. We could virtualize the list though.
What's taking up resources is loading the streams. We should stop looking for streams beyond the next 3-5 items, and load them as necessary.

**Comment by Septimus** [comment]
I have began development on this.

**Comment by 1lluzi0nzz** [comment]
I haven't seen any activity on this issue, can I work on it?

**Comment by HaiDang666** [comment]
yes, I assigned to  you

**Comment by 1lluzi0nzz** [comment]
Thank you, will let you know when I have news!

**Comment by jammet** [comment]
To help a little more with what has been a huge issue for me, is that queuing tracks using somewhat slower connections (SDSL here, you can stream full 1080 video streams just fine, but that's the limit), takes a very long time. Especially if you queue *multiple* tracks, the internet connection is clogged for a *very* long time, and with about 100 Tracks you will be waiting 10-15 minutes until playback even just starts.

It would be very helpful to queue in such a way that this is taken into consideration, by option, by measured approach, or otherwise. If you just add one track, then load whatever data you require, and then start playback (if desired), playback will be continuous. A bit of wait time really is needed. If that's not there, like today, I can't queue anything other than individual, single tracks. 

It might also help to limit the maximum amount of OPEN connections!

**Comment by nukeop** [comment]
Happy to say this is finally implemented
